### ISSUE TITLE
Add busted globals

### ISSUE THREAD

**Issue by rm-code** [AtomLinter/linter-luacheck#22]
Busted is a unit testing framework and luacheck can automatically ignore busted-related globals via:

```
luacheck ... --std max+busted
```

Is there a way to make linter-luacheck behave the same without having to add all the globals manually?

**Comment by xpol** [comment]
There are ways:

## 1. Use [luacheck config file](http://luacheck.readthedocs.io/en/0.12.0/config.html) `.luacheckrc` file at root of your project root:

`.luacheckrc`:
```lua
files['spec/*_spec.lua'].std = 'max+busted'
```

or at spec directory:

`spec/.luacheckrc`
```lua
files['*_spec.lua'].std = 'max+busted'
```

## 2. Use [inline options](http://luacheck.readthedocs.io/en/0.12.0/inline.html) at first line of your busted spec files.

```lua
-- luacheck: std max+busted

describe(....., function()
  -- ...
end)
```

**Comment by rm-code** [comment]
Thanks for the quick reply. Works like a charm now!
