### ISSUE TITLE
Move to ES6

### ISSUE THREAD

**Issue by Positive07** [AtomLinter/linter-luacheck#29]
As you stated we should forget about CoffeeScript and move to ES6 with Babel. I'm opening this issue for reference only (I may even work on this)

**Comment by Arcanemagus** [comment]
If you'd like to help maintain this package I can add you to the team with rights on here 😉.

**Comment by Positive07** [comment]
That would be really cool! If you are fine with it, I'm on!

**Comment by Positive07** [comment]
All right, I'm having some problems with this, and I don't really know the issue:
* [Travis](https://travis-ci.org/Positive07/linter-luacheck)
* [CircleCI](https://circleci.com/gh/Positive07/linter-luacheck)
* [AppVeyor](https://ci.appveyor.com/project/Positive07/linter-luacheck)

The branch is [this one](https://github.com/Positive07/linter-luacheck/tree/ES6)

**Comment by Arcanemagus** [comment]
`'use-babel';` (your branch) vs `'use babel';`.

**Comment by Arcanemagus** [comment]
@xpol Any objection to bringing in @Positive07 to this project?

**Comment by Positive07** [comment]
All right! There is only one failing test which I have no clue about, it looks like Atom reports the package as Inactive for some reason... is this some kind of race condition?

**Comment by Arcanemagus** [comment]
This will be simpler if you start a PR from that branch so we can do reviews there.

To fix your specs as they are currently written you will need to bring in the (somewhat badly named) `jasmine-fix` module and use the `it`/`beforeEach` from there to support `async`/`await`. The default Jasmine 1.3 environment that Atom uses doesn't support them normally.

**Comment by Positive07** [comment]
I did both of the things proposed here, a PR and now it's using `jasmine-fix` which made everything work inmediately!
