### ISSUE TITLE
.luacheckrc is no longer read

### ISSUE THREAD

**Issue by Nexela** [AtomLinter/linter-luacheck#32]
Latest update ignores .luacheckrc

Possibly due to the new "standards" settings

**Comment by Arcanemagus** [comment]
Hmmm, this sounds like a bug in `luacheck` itself. Does it work on its own in the CLI if you specify `luacheck --std _G foo.lua`?

**Comment by Nexela** [comment]
Using https://github.com/Nexela/Factorio-luacheckrc
on this file
https://github.com/Nexela/PickerExtended/blob/master/control.lua

running luacheck control.lua from the command line shows 0 warnings
running luacheck --std _G control.lua shows 25 warnings
using linter-luacheck 1.2.0 shows 0 warnings
using linter-luacheck 2.0.0 shows 16 warnings

**Comment by Positive07** [comment]
First, this is a bug in Luacheck itself, `.luacheckrc` should always override the CLI options or at least add to them.

There is a way to fix this, we can make the default value equal to the empty array, which means that `--std` wouldn't be passed as a command by default. This means, for example, that if you set the Standards config to `busted` it would only allow you to use globals defined by `busted`, if you wanted to add this to the default standard you would need to write `_G, busted`... is this better?

Alternatively this option could be additive as proposed by @Arcanemagus which would mean that `busted` would be passed as `--std +busted` which means `default + busted`, the issue with this is that if you want for example only values in the `luajit` standard but you are running Luacheck in Lua 5.3, setting the config to `luajit` would actually mean `default + luajit` or `lua53c + luajit` which wouldn't be what you want.

So both has it's pro and cons, a third option would be to be able to `Enable/Disable` this configuration... Which I don't really like, I personally  favour the first option.

Anyway I reported it over at Luacheck

**Comment by Arcanemagus** [comment]
How about we change the default to nothing, and leave it up to the user to handle adding `_G` if they desire?

That works around this bug in `luacheck` and doesn't put this in the situation of always appending to the default.

**Comment by Positive07** [comment]
Yeah first option then! I'll push that immediately, I'll may add a tip later to the README saying that you can use `_G, busted` if they want additive behaviour

**Comment by Positive07** [comment]
Yes this should fix the issue, it looks like this is intended behaviour in Luacheck so the way we dealt with it is the best way.

In a near feature Luacheck will implement `Global Config` (mpeterv/luacheck#102) and there will be no need for this package to provide any configuration at all except for the Executable Path
