### ISSUE TITLE
XRegExp is not a function

### ISSUE THREAD

**Issue by urzds** [AtomLinter/linter-luacheck#9]
Upon every start Atom shows the following error:
```
TypeError: XRegExp is not a function
  at Object.parse (@HOME@/.atom/packages/linter-luacheck/node_modules/atom-linter/lib/helpers.js:424:18)
  at @HOME@/.atom/packages/linter-luacheck/lib/init.coffee:61:26
  at process._tickDomainCallback (node.js:411:9)
```

There is no bug-report link provided and no way to copy the stacktrace and version information.

Atom 1.5.3
linter-luacheck 1.1.4

**Comment by steelbrain** [comment]
Can you please uninstall and reinstall the package and see if it fixes this error for you?

**Comment by urzds** [comment]
> Can you please uninstall and reinstall the package and see if it fixes this error for you?

That causes #10.

**Comment by urzds** [comment]
After reloading Atom (Ctrl+Alt+R), this issue is gone.
